# Generated by Django 5.2.9 on 2025-12-25 03:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImagingStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateTimeField()),
                ('modality', models.CharField(choices=[('CT', 'CT SCAN'), ('MRI', 'MRI'), ('XRAY', 'X-Ray'), ('ULTRASOUND', 'Ultrasound')], max_length=20)),
                ('body_part', models.CharField(help_text='e.g. Chest, Lung, Brain', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archieved')], default='pending', max_length=20)),
                ('referring_physician', models.CharField(blank=True, max_length=200)),
                ('clinical_notes', models.TextField(blank=True, help_text='Reason for study')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Imaging Studies',
                'ordering': ['-study_date'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.TextField(help_text='Detailed radiologist findings')),
                ('impression', models.TextField(help_text='Summary/conclusion')),
                ('severity', models.CharField(choices=[('normal', 'Normal'), ('minor', 'Minor Finding'), ('moderate', 'Moderate Concern'), ('severe', 'Severe - Urgent')], default='normal', max_length=20)),
                ('recommendations', models.TextField(blank=True)),
                ('diagnosed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('radiologist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to=settings.AUTH_USER_MODEL)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='medical_imaging.imagingstudy')),
            ],
            options={
                'verbose_name_plural': 'Diagnoses',
                'ordering': ['-diagnosed_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_record_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='medical_imaging.hospital')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='imagingstudy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_studies', to='medical_imaging.patient'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('download', 'Downloaded')], max_length=20)),
                ('resource_type', models.CharField(help_text='e.g., Patient, ImagingStudy', max_length=50)),
                ('resource_id', models.IntegerField(help_text='ID of the affected record')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='medical_ima_timesta_662f27_idx'), models.Index(fields=['user', '-timestamp'], name='medical_ima_user_id_78698e_idx'), models.Index(fields=['resource_type', 'resource_id'], name='medical_ima_resourc_ac2fa0_idx')],
            },
        ),
        migrations.CreateModel(
            name='DicomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(upload_to='dicom_image/%Y/%m/%d/')),
                ('instance_number', models.IntegerField(help_text='Image sequence numer in study', validators=[django.core.validators.MinValueValidator(1)])),
                ('since_thinkness', models.DecimalField(blank=True, decimal_places=2, help_text='in mm', max_digits=5, null=True)),
                ('pixel_spacing', models.CharField(blank=True, max_length=50)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='medical_imaging.imagingstudy')),
            ],
            options={
                'ordering': ['instance_number'],
                'unique_together': {('study', 'instance_number')},
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['medical_record_number'], name='medical_ima_medical_4dc1be_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['hospital', 'last_name'], name='medical_ima_hospita_aacdc8_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['patient', '-study_date'], name='medical_ima_patient_862617_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['status'], name='medical_ima_status_a795fd_idx'),
        ),
    ]
