# Generated by Django 5.2.9 on 2025-12-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_imaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicomimage',
            old_name='since_thinkness',
            new_name='slice_thickness',
        ),
    ]
