# Generated by Django 6.0 on 2025-12-26 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_imaging', '0003_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Website - Contact Messages'},
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['-diagnosed_at'], name='medical_ima_diagnos_ba9743_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['severity', '-diagnosed_at'], name='medical_ima_severit_86c6ce_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['radiologist', '-diagnosed_at'], name='medical_ima_radiolo_f7d943_idx'),
        ),
        migrations.AddIndex(
            model_name='dicomimage',
            index=models.Index(fields=['study', 'instance_number'], name='medical_ima_study_i_fe9f26_idx'),
        ),
        migrations.AddIndex(
            model_name='dicomimage',
            index=models.Index(fields=['-uploaded_at'], name='medical_ima_uploade_6f7702_idx'),
        ),
        migrations.AddIndex(
            model_name='dicomimage',
            index=models.Index(fields=['file_size_bytes'], name='medical_ima_file_si_b64014_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['name'], name='medical_ima_name_af332e_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['created_at'], name='medical_ima_created_c78a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['modality', '-study_date'], name='medical_ima_modalit_d18b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['status', '-study_date'], name='medical_ima_status_4e8a21_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['-study_date'], name='medical_ima_study_d_5da49d_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingstudy',
            index=models.Index(fields=['body_part'], name='medical_ima_body_pa_d19d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['hospital', 'created_at'], name='medical_ima_hospita_de2f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['gender'], name='medical_ima_gender_83f6ac_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['date_of_birth'], name='medical_ima_date_of_b107ce_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['email'], name='medical_ima_email_ea62d6_idx'),
        ),
    ]
