# Generated by Django 6.0 on 2025-12-26 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_imaging', '0004_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomimage',
            name='bits_allocated',
            field=models.IntegerField(blank=True, help_text='Bits allocated per pixel', null=True),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='bits_stored',
            field=models.IntegerField(blank=True, help_text='Bits stored per pixel', null=True),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='columns',
            field=models.IntegerField(blank=True, help_text='Image width in pixels', null=True),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='dicom_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Complete DICOM metadata as JSON'),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='is_dicom',
            field=models.BooleanField(default=False, help_text='True if file is valid DICOM format'),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Equipment manufacturer', max_length=200),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='manufacturer_model',
            field=models.CharField(blank=True, help_text='Equipment model', max_length=200),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='rescale_intercept',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rescale intercept for Hounsfield units', max_digits=10),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='rescale_slope',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Rescale slope for Hounsfield units', max_digits=10),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='rows',
            field=models.IntegerField(blank=True, help_text='Image height in pixels', null=True),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='slice_location',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Slice location in mm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='sop_instance_uid',
            field=models.CharField(blank=True, help_text='SOP Instance UID (unique DICOM identifier)', max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='window_center',
            field=models.CharField(blank=True, help_text='Window center for display', max_length=50),
        ),
        migrations.AddField(
            model_name='dicomimage',
            name='window_width',
            field=models.CharField(blank=True, help_text='Window width for display', max_length=50),
        ),
        migrations.AlterField(
            model_name='dicomimage',
            name='instance_number',
            field=models.IntegerField(help_text='Image sequence number in study', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='dicomimage',
            name='pixel_spacing',
            field=models.CharField(blank=True, help_text='Pixel spacing (row, column)', max_length=50),
        ),
        migrations.AlterField(
            model_name='dicomimage',
            name='slice_thickness',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Slice thickness in mm', max_digits=5, null=True),
        ),
    ]
