# Generated by Django 5.2.9 on 2025-12-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_imaging', '0005_dicomimage_bits_allocated_dicomimage_bits_stored_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomimage',
            name='slice_location',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Slice location in mm', max_digits=15, null=True),
        ),
    ]
