# Generated by Django 5.2.9 on 2025-12-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_imaging', '0007_alter_dicomimage_slice_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomimage',
            name='slice_location',
            field=models.FloatField(blank=True, help_text='Slice location in mm', null=True),
        ),
    ]
