# Generated by Django 5.2.9 on 2025-12-27 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_imaging', '0009_taskstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(help_text='PDF report file', upload_to='patient_reports/')),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('studies_count', models.IntegerField(default=0, help_text='Number of studies included in this report')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID that generated this report', max_length=255)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='medical_imaging.patient')),
            ],
            options={
                'verbose_name': 'Patient Report',
                'verbose_name_plural': 'Patient Reports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['patient', '-generated_at'], name='medical_ima_patient_e062ca_idx'), models.Index(fields=['generated_by', '-generated_at'], name='medical_ima_generat_fa6a4d_idx')],
            },
        ),
    ]
