# Generated by Django 5.2.9 on 2025-12-28 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_imaging', '0010_patientreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='actor_type',
            field=models.CharField(choices=[('user', 'User'), ('system', 'System'), ('api', 'API Client')], default='user', help_text='Type of actor performing the action', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='tenant_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Hospital ID for multi-tenant isolation', null=True),
        ),
        migrations.AddField(
            model_name='imagingstudy',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details if processing failed'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('view', 'Viewed'), ('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('download', 'Downloaded'), ('process', 'Processed'), ('failed', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagingstudy',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('archived', 'Archieved')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor_type', '-timestamp'], name='medical_ima_actor_t_646dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant_id', '-timestamp'], name='medical_ima_tenant__d97483_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant_id', 'action', '-timestamp'], name='medical_ima_tenant__a6004b_idx'),
        ),
    ]
