# Generated by Django 5.2.9 on 2025-12-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_imaging', '0011_auditlog_actor_type_auditlog_tenant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingstudy',
            name='processing_version',
            field=models.CharField(blank=True, default='', help_text='Version of DICOM processing algorithm used (e.g., v1.2.0)', max_length=50),
        ),
        migrations.AddField(
            model_name='imagingstudy',
            name='retention_until',
            field=models.DateField(blank=True, db_index=True, help_text='Date when this study can be purged (HIPAA: 6 years from last activity)', null=True),
        ),
    ]
