"""
Django settings for firstproject project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z4$io*ia5bn-slpckf4x^y6s^fq&!-e=60j(-5q$43n6ng7)i='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'corsheaders',
    'django_filters',

    # Django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.headless',
    'allauth.mfa',
    'allauth.usersessions',

    # Social providers (optional - add as needed)
    # 'allauth.socialaccount.providers.google',
    # 'allauth.socialaccount.providers.github',

    # Your apps
    'firstapp',
    'medical_imaging',
    'storages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS - must be before CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'firstproject.middleware.DisableCSRFForAllauthMiddleware',  # Disable CSRF for allauth headless
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required for allauth
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'firstproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'firstproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
           'ENGINE': 'django.db.backends.mysql',
           'NAME': 'django_db',
           'USER': 'root',
           'PASSWORD': 'Zedrop@78',
           'HOST': 'localhost',
           'PORT': 3306,
           'OPTIONS':{
               'init_command':"SET sql_mode='STRICT_TRANS_TABLES'"
           }

    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework Configuration
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'allauth.headless.rest_framework.authentication.SessionTokenAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticatedOrReadOnly',
#     ],
#     'DEFAULT_FILTER_BACKENDS': [
#         'django_filters.rest_framework.DjangoFilterBackend',
#         'rest_framework.filters.SearchFilter',
#         'rest_framework.filters.OrderingFilter',
#     ],
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE': 20
# }

  # Django REST Framework Settings
REST_FRAMEWORK = {
      'DEFAULT_AUTHENTICATION_CLASSES': [
          'rest_framework.authentication.SessionAuthentication',
           'rest_framework.authentication.BasicAuthentication', 
      ],
      'DEFAULT_PERMISSION_CLASSES': [
        #   'rest_framework.permissions.IsAuthenticatedOrReadOnly',
               'rest_framework.permissions.AllowAny',  # Change to AllowAny for testing
      ],
      'DEFAULT_FILTER_BACKENDS': [
          'django_filters.rest_framework.DjangoFilterBackend',
          'rest_framework.filters.SearchFilter',
          'rest_framework.filters.OrderingFilter',
      ],
      'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
      'PAGE_SIZE': 20,
  }
# CORS Configuration for Next.js
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'https://localhost:3000'
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-session-token',  # Required for django-allauth headless
]

# CSRF Configuration - Allow requests from Next.js
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'https://localhost:3000'
]

# Exempt allauth headless endpoints from CSRF (they use session tokens)
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True

# Django-Allauth Configuration
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth settings (updated to new format)
ACCOUNT_LOGIN_METHODS = {'email'}  # Use email for login
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*']  # Only one password required
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # Change to 'mandatory' for production
ACCOUNT_USER_MODEL_USERNAME_FIELD = None  # No username field

# Headless mode configuration
HEADLESS_ONLY = True  # Disable allauth views, API only

# Frontend URLs (for email verification links, password reset, etc.)
HEADLESS_FRONTEND_URLS = {
    'account_confirm_email': 'http://localhost:3000/auth/verify-email/{key}',
    'account_reset_password': 'http://localhost:3000/auth/reset-password',
    'account_reset_password_from_key': 'http://localhost:3000/auth/reset-password/{key}',
    'account_signup': 'http://localhost:3000/auth/signup',
}

# Token strategy - using Session Tokens (default)
HEADLESS_TOKEN_STRATEGY = 'allauth.headless.tokens.sessions.SessionTokenStrategy'

# Email backend (for development - prints to console)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
USE_S3 = config('USE_S3', default=True, cast=bool)

if USE_S3:
      # AWS Credentials (DO NOT commit these to git!)
      AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
      AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
      AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
      AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='ap-south-1')

      # S3 Settings
      AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
      AWS_S3_OBJECT_PARAMETERS = {
          'CacheControl': 'max-age=86400',  # 1 day cache
      }
      AWS_DEFAULT_ACL = None  # Don't set ACL (use bucket policy)
      AWS_S3_FILE_OVERWRITE = False  # Don't overwrite files with same name

      # Storage backends (Django 5+ format)
      STORAGES = {
          "default": {
              "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
          },
          "staticfiles": {
              "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
          },
      }

      # Media files will be stored at: https://medical-imaging-dev-pushkar.s3.amazonaws.com/dicom_images/...
      MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
else:
      # Local storage (development fallback)
      MEDIA_URL = '/media/'
      MEDIA_ROOT = BASE_DIR/ 'media'